import { describe, it, expect, vi } from 'vitest';
import { MockProvider } from './mockProvider';
import type { BatchAnswerInput, DraftAnswerInput } from '../types';

describe('MockProvider', () => {
  const provider = new MockProvider();
  
  it('should be properly initialized with correct properties', () => {
    expect(provider.id).toBe('mock');
    expect(provider.label).toBe('Mock');
    expect(provider.mode).toBe('local');
  });

  it('should report as configured', () => {
    expect(provider.configured()).toBe(true);
  });

  it('should pass health check', async () => {
    expect(await provider.healthCheck()).toBe(true);
  });

  it('should generate a draft answer', async () => {
    const input: DraftAnswerInput = {
      question: 'Tell me about yourself',
      field: { fieldId: 'field1', type: 'text' },
      context: 'Some context here'
    };

    const result = await provider.generateAnswerDraft(input);
    
    expect(result).toBeDefined();
    expect(result.text).toBe('Draft answer for "Tell me about yourself". Review and personalize before using.');
    expect(result.confidence).toBe(0.35);
    expect(result.provider).toBe('mock');
    expect(result.model).toBeUndefined();
  });

  it('should generate batch answer drafts', async () => {
    const input: BatchAnswerInput = {
      fields: [
        { field: { fieldId: 'field1', type: 'text' }, question: 'Question 1' },
        { field: { fieldId: 'field2', type: 'textarea' }, question: 'Question 2' }
      ],
      context: 'Some context here'
    };

    const result = await provider.generateAnswerDrafts(input);
    
    expect(result).toHaveLength(2);
    expect(result[0].fieldId).toBe('field1');
    expect(result[1].fieldId).toBe('field2');
    expect(result[0].text).toBe('Draft answer for "Question 1". Review and personalize before using.');
    expect(result[1].text).toBe('Draft answer for "Question 2". Review and personalize before using.');
    expect(result[0].confidence).toBe(0.35);
    expect(result[1].confidence).toBe(0.35);
    expect(result[0].provider).toBe('mock');
    expect(result[1].provider).toBe('mock');
    expect(result[0].model).toBeUndefined();
    expect(result[1].model).toBeUndefined();
  });

  it('should tailor resume', async () => {
    const input = {
      resumeText: 'My resume text here',
      jobDescription: 'Job description here',
      userContext: 'User context here'
    };

    const result = await provider.tailorResume(input);
    
    expect(result).toBeDefined();
    expect(result.text).toContain('Tailored resume draft generated by the mock provider.');
    expect(result.confidence).toBe(0.3);
    expect(result.provider).toBe('mock');
    expect(result.model).toBeUndefined();
  });
});