import { AIProvider, DraftAnswerInput, DraftAnswerResult } from "../types";

export class MockProvider implements AIProvider {
  id = "mock";
  label = "Mock";
  mode = "local" as const;

  configured() {
    return true;
  }

  async healthCheck() {
    return true;
  }

  async generateAnswerDraft(input: DraftAnswerInput): Promise<DraftAnswerResult> {
    return {
      text: `Draft answer for "${input.question}". Review and personalize before using.`,
      confidence: 0.35,
      sourceContext: {
        contextUsed: "mock",
        fieldId: input.field.fieldId,
      },
      provider: this.id,
    };
  }

  async tailorResume(input: {
    resumeText: string;
    jobDescription: string;
    userContext: string;
  }): Promise<DraftAnswerResult> {
    return {
      text: [
        "Tailored resume draft generated by the mock provider.",
        "",
        "Use this as a review placeholder. Configure DeepSeek, OpenAI, or Ollama for real tailoring.",
        "",
        "Original resume excerpt:",
        input.resumeText.slice(0, 1200),
        "",
        "Job description signals:",
        input.jobDescription.slice(0, 800),
        "",
        "Saved user context excerpt:",
        input.userContext.slice(0, 800),
      ].join("\n"),
      confidence: 0.3,
      sourceContext: {
        contextUsed: "resume_job_description_user_context",
        provider: this.id,
      },
      provider: this.id,
    };
  }
}
